#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Batched intent refine runner.

Architecture
------------
Copilot CLI **must** run inside a real PowerShell console (TTY).  Calling it
via a Python subprocess (even with inherited streams) causes it to enter a
slow agentic exploration mode or deny write permissions.

Correct flow:
  1. Python prepares batch-subset JSON files and prompt files.
  2. Python writes a PS1 runner script and executes it via
       powershell.exe -File <script>
     which gives copilot.cmd a proper Windows console session.
  3. Python merges all batch output files into the final JSON.

Usage
-----
  python run_intent_refine_batched.py              # full run (skip finished batches)
  python run_intent_refine_batched.py --merge-only # merge already-produced outputs
  python run_intent_refine_batched.py --prepare-only # prepare prompts, print PS1 path
"""

import json
import os
import subprocess
import sys
from datetime import datetime

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "copilot-cli"))

from generator_intent_refine_copilot import GeneratorIntentRefineCopilot
from log_manager import get_logger

logger = get_logger("batched_intent_refine")

def auto_partition_by_rows(all_rows: list, target_rows: int) -> list:
    """Group cases into batches aiming for ~target_rows rows per batch."""
    from collections import OrderedDict
    case_row_counts: OrderedDict = OrderedDict()
    for r in all_rows:
        cid = str(r.get("case_id", ""))
        case_row_counts[cid] = case_row_counts.get(cid, 0) + 1

    batches: list = []
    current_batch: list = []
    current_count = 0
    for cid, n in case_row_counts.items():
        if current_batch and current_count + n > target_rows * 1.5:
            batches.append(current_batch)
            current_batch = [cid]
            current_count = n
        else:
            current_batch.append(cid)
            current_count += n
    if current_batch:
        batches.append(current_batch)
    return batches


# The -p argument template passed to copilot.cmd.
# {prompt_file} is replaced with the actual path at runtime.
COPILOT_P_TEMPLATE = (
    "Read the file {prompt_file} carefully. "
    "Execute all instructions in that file exactly as specified, "
    "and write the output JSON to the path given in the file's instructions. "
    "Do not ask for clarification — just complete the task."
)


def load_json(path: str) -> dict:
    with open(path, encoding="utf-8-sig") as f:
        return json.load(f)


def save_json(path: str, data: dict) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def subset_json(full_data: dict, case_ids: list) -> dict:
    """Return a copy of full_data containing only rows for the given case_ids."""
    id_set = set(case_ids)
    filtered = [r for r in full_data["rows"] if r["case_id"] in id_set]
    return {
        "status": full_data.get("status", "ok"),
        "meta": dict(full_data.get("meta", {}), rows=len(filtered)),
        "rows": filtered,
    }


def build_ps1_runner(pending: list, ps1_path: str) -> None:
    """Write a PowerShell script that runs copilot.cmd for each pending batch.

    pending: list of (prompt_path, output_path, label) tuples
    """
    lines = [
        "# Auto-generated by run_intent_refine_batched.py — do not edit manually.",
        "# Runs copilot.cmd for each pending batch sequentially.",
        "$ErrorActionPreference = 'Stop'",
        "",
    ]
    for prompt_path, output_path, label in pending:
        # Escape backslashes for PowerShell double-quoted strings
        prompt_ps = prompt_path.replace("\\", "\\\\")
        output_ps = output_path.replace("\\", "\\\\")
        p_arg = COPILOT_P_TEMPLATE.format(prompt_file=prompt_ps)
        lines += [
            f'Write-Host "--- {label} ---" -ForegroundColor Cyan',
            f'copilot.cmd -p "{p_arg}" --allow-all',
            f'if (-not (Test-Path "{output_ps}")) {{',
            f'    Write-Error "Batch output not found: {output_ps}"',
            f'    exit 1',
            f'}}',
            f'Write-Host "[OK] {label} done." -ForegroundColor Green',
            "",
        ]
    lines.append('Write-Host "All batches complete." -ForegroundColor Green')
    with open(ps1_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def run_ps1(ps1_path: str, project_root: str) -> int:
    """Execute the PS1 runner via powershell.exe -File.

    powershell.exe is a proper console host, so copilot.cmd runs with a real
    TTY and behaves identically to running it manually in a terminal.
    Returns the exit code.
    """
    cmd = [
        "powershell.exe",
        "-ExecutionPolicy", "Bypass",
        "-File", ps1_path,
    ]
    proc = subprocess.run(cmd, cwd=project_root)
    return proc.returncode


def merge_batches(all_rows: list, tmp_dir: str, n_batches: int) -> dict:
    """Load all batchN_output.json files and build the merged row map."""
    refined_map: dict = {}
    for batch_idx in range(1, n_batches + 1):
        output_path = os.path.join(tmp_dir, f"batch{batch_idx}_output.json")
        if not os.path.exists(output_path):
            print(f"  [WARN] batch{batch_idx}_output.json missing — using raw rows for that batch")
            continue
        refined_data = load_json(output_path)
        for row in refined_data["rows"]:
            key = (row["case_id"], row["step_no"], row["sub_step_no"])
            refined_map[key] = row
        print(f"  [LOADED] batch{batch_idx}: {len(refined_data['rows'])} rows")

    final_rows = []
    replaced = kept_raw = 0
    for raw_row in all_rows:
        key = (raw_row["case_id"], raw_row["step_no"], raw_row["sub_step_no"])
        if key in refined_map:
            final_rows.append(refined_map[key])
            replaced += 1
        else:
            final_rows.append(raw_row)
            kept_raw += 1
    return {"replaced": replaced, "kept_raw": kept_raw, "rows": final_rows}


def main():
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, metavar="RAW_JSON",
                        help="Path to the raw atomized actions JSON (*.testcase_actions.stepwise.raw.vN.json)")
    parser.add_argument("--output", required=True, metavar="REFINED_JSON",
                        help="Path to write the final intent-refined actions JSON")
    parser.add_argument("--batch-rows", type=int, default=30, metavar="N",
                        help="Target rows per batch (default: 30)")
    parser.add_argument("--merge-only", action="store_true",
                        help="Skip Copilot; just merge existing batchN_output.json files")
    parser.add_argument("--prepare-only", action="store_true",
                        help="Prepare prompt files and print the PS1 path; do not run Copilot")
    args = parser.parse_args()

    project_root = os.path.dirname(os.path.abspath(__file__))
    tmp_dir = os.path.join(project_root, "tmp")
    os.makedirs(tmp_dir, exist_ok=True)

    raw_path   = args.input if os.path.isabs(args.input) else os.path.join(project_root, args.input)
    final_path = args.output if os.path.isabs(args.output) else os.path.join(project_root, args.output)

    print(f"Loading raw input: {args.input}")
    full_data = load_json(raw_path)
    all_rows = full_data["rows"]
    print(f"Total rows: {len(all_rows)}")
    batches = auto_partition_by_rows(all_rows, args.batch_rows)
    print(f"Auto-partitioned into {len(batches)} batch(es) targeting ~{args.batch_rows} rows each")

    # ------------------------------------------------------------------ merge-only
    if args.merge_only:
        print("\n[MERGE-ONLY] Skipping Copilot, merging existing batch outputs...")
        result = merge_batches(all_rows, tmp_dir, len(batches))
        _write_final(full_data, result, final_path)
        return

    # ----------------------------------------- Step 1: prepare all prompt files
    pending: list = []   # (prompt_path, output_path, label)

    for batch_idx, case_ids in enumerate(batches, start=1):
        label = f"Batch {batch_idx} ({case_ids[0]}..{case_ids[-1]})"
        subset_path = os.path.join(tmp_dir, f"batch{batch_idx}_input.json")
        output_path = os.path.join(tmp_dir, f"batch{batch_idx}_output.json")

        if os.path.exists(output_path):
            print(f"[BATCH {batch_idx}] output already exists — will reuse in merge")
            continue

        # Write subset JSON
        subset = subset_json(full_data, case_ids)
        save_json(subset_path, subset)

        # Build prompt file (no Copilot call yet)
        ts = datetime.now().strftime("%Y%m%d_%H%M%S") + f"_b{batch_idx}"
        gen = GeneratorIntentRefineCopilot(
            temp_dir=tmp_dir,
            copilot_cmd="copilot.cmd",
            project_root=project_root,
        )
        prompt_path = gen.prepare_prompt_file(
            input_action_file=subset_path,
            output_action_file=output_path,
            skip_case_ids=[],
            timestamp=ts,
        )
        kb = os.path.getsize(prompt_path) // 1024
        print(f"[BATCH {batch_idx}] prompt ready: {os.path.basename(prompt_path)}  ({kb} KB)")
        pending.append((prompt_path, output_path, label))

    if not pending:
        print("\n[INFO] All batch outputs already exist — skipping to merge.")
    elif args.prepare_only:
        # ----------------------------------- prepare-only: print PS1 and exit
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        ps1_path = os.path.join(tmp_dir, f"run_copilot_batches_{ts}.ps1")
        build_ps1_runner(pending, ps1_path)
        print(f"\n[PREPARE-ONLY] PS1 runner written to:\n  {ps1_path}")
        print("\nRun it in PowerShell:")
        print(f"  & \"{ps1_path}\"")
        print("\nThen re-run this script with --merge-only to merge outputs.")
        return
    else:
        # --------------------------------------- Step 2: build & run PS1 runner
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        ps1_path = os.path.join(tmp_dir, f"run_copilot_batches_{ts}.ps1")
        build_ps1_runner(pending, ps1_path)
        print(f"\n[COPILOT] Running {len(pending)} batch(es) via PowerShell console...")
        print(f"  PS1: {ps1_path}")
        rc = run_ps1(ps1_path, project_root)
        if rc != 0:
            print(f"[ERROR] PS1 runner exited with code {rc}. Check output above.")
            sys.exit(rc)
        print("[COPILOT] All batches done.")

    # ------------------------------------------------------------------ Step 3: merge
    print(f"\n{'='*60}")
    print("[MERGE] Building final output...")
    result = merge_batches(all_rows, tmp_dir, len(batches))
    _write_final(full_data, result, final_path)


def _write_final(full_data: dict, result: dict, final_path: str) -> None:
    final_data = {
        "status": "ok",
        "meta": dict(full_data.get("meta", {}),
                     rows=len(result["rows"]),
                     mode="copilot_batched"),
        "rows": result["rows"],
    }
    save_json(final_path, final_data)
    print(f"  refined rows : {result['replaced']}")
    print(f"  kept raw     : {result['kept_raw']}")
    print(f"  total rows   : {len(result['rows'])}")
    print(f"\n[ALL DONE] Final output: {final_path}")


if __name__ == "__main__":
    main()

