#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Batched atomize runner — Stage C of the testcase_to_steps workflow.

Architecture
------------
Copilot CLI must run inside a real PowerShell console (TTY).  Calling it via
a Python subprocess causes it to enter agentic exploration mode or deny write
permissions.

Correct flow:
  1. Python reads the cleaned JSON, partitions cases into batches, writes
     self-contained prompt files (one per batch) and a PS1 runner script.
  2. powershell.exe -File <ps1> runs copilot.cmd for each batch sequentially.
  3. Python merges all batch outputs into the final raw.v4.json.

Usage
-----
  python run_atomize_batched.py --input <cleaned.json> --output <raw.v4.json>
  python run_atomize_batched.py --input ... --output ... --prepare-only
  python run_atomize_batched.py --input ... --output ... --merge-only
  python run_atomize_batched.py --input ... --output ... --batch-size 4
"""

import argparse
import json
import os
import subprocess
import sys
from collections import OrderedDict
from datetime import datetime

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "copilot-cli"))

from generator_atomize_copilot import GeneratorAtomizeCopilot
from log_manager import get_logger

logger = get_logger("batched_atomize")

COPILOT_P_TEMPLATE = (
    "Read the file {prompt_file} carefully. "
    "Execute all instructions in that file exactly as specified, "
    "and write the output JSON to the path given in the file's instructions. "
    "Do not ask for clarification — just complete the task."
)


def load_json(path: str) -> dict:
    with open(path, encoding="utf-8-sig") as f:
        return json.load(f)


def save_json(path: str, data: dict) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def auto_partition_by_count(worksheet: list, batch_size: int) -> list:
    """Split cases into batches of at most batch_size cases each."""
    batches = []
    for i in range(0, len(worksheet), batch_size):
        batch_cases = worksheet[i : i + batch_size]
        batches.append([str(c["case_id"]) for c in batch_cases])
    return batches


def build_ps1_runner(pending: list, ps1_path: str) -> None:
    lines = [
        "# Auto-generated by run_atomize_batched.py — do not edit manually.",
        "$ErrorActionPreference = 'Stop'",
        "",
    ]
    for prompt_path, output_path, label in pending:
        prompt_ps = prompt_path.replace("\\", "\\\\")
        output_ps = output_path.replace("\\", "\\\\")
        p_arg = COPILOT_P_TEMPLATE.format(prompt_file=prompt_ps)
        lines += [
            f'Write-Host "--- {label} ---" -ForegroundColor Cyan',
            f'copilot.cmd -p "{p_arg}" --allow-all',
            f'if (-not (Test-Path "{output_ps}")) {{',
            f'    Write-Error "Batch output not found: {output_ps}"',
            f'    exit 1',
            f'}}',
            f'Write-Host "[OK] {label} done." -ForegroundColor Green',
            "",
        ]
    lines.append('Write-Host "All batches complete." -ForegroundColor Green')
    with open(ps1_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def run_ps1(ps1_path: str, project_root: str) -> int:
    cmd = ["powershell.exe", "-ExecutionPolicy", "Bypass", "-File", ps1_path]
    proc = subprocess.run(cmd, cwd=project_root)
    return proc.returncode


def _detect_existing_batches(tmp_dir: str, prefix: str) -> int:
    n = 0
    while os.path.exists(os.path.join(tmp_dir, f"{prefix}{n + 1}_output.json")):
        n += 1
    return n


def merge_batches(tmp_dir: str, n_batches: int, prefix: str = "atomize_batch") -> list:
    if n_batches == 0:
        n_batches = _detect_existing_batches(tmp_dir, prefix)
        print(f"  [AUTO] Detected {n_batches} batch output file(s)")
    all_rows = []
    for batch_idx in range(1, n_batches + 1):
        output_path = os.path.join(tmp_dir, f"{prefix}{batch_idx}_output.json")
        if not os.path.exists(output_path):
            print(f"  [WARN] {prefix}{batch_idx}_output.json missing — skipping")
            continue
        data = load_json(output_path)
        rows = data.get("rows", [])
        all_rows.extend(rows)
        print(f"  [LOADED] batch{batch_idx}: {len(rows)} rows")
    return all_rows


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, metavar="CLEANED_JSON")
    parser.add_argument("--output", required=True, metavar="RAW_V4_JSON")
    parser.add_argument("--batch-size", type=int, default=5, metavar="N",
                        help="Cases per batch (default: 5)")
    parser.add_argument("--merge-only", action="store_true")
    parser.add_argument("--prepare-only", action="store_true")
    args = parser.parse_args()

    project_root = os.path.dirname(os.path.abspath(__file__))
    tmp_dir = os.path.join(project_root, "tmp")
    os.makedirs(tmp_dir, exist_ok=True)

    cleaned_path = args.input if os.path.isabs(args.input) else os.path.join(project_root, args.input)
    final_path   = args.output if os.path.isabs(args.output) else os.path.join(project_root, args.output)

    print(f"Loading cleaned input: {args.input}")
    cleaned_data = load_json(cleaned_path)
    worksheet = cleaned_data.get("Worksheet", [])
    print(f"Total cases: {len(worksheet)}")

    batches = auto_partition_by_count(worksheet, args.batch_size)
    print(f"Partitioned into {len(batches)} batch(es) of up to {args.batch_size} cases each")

    prefix = "atomize_batch"

    # ------------------------------------------------------------------ merge-only
    if args.merge_only:
        print("\n[MERGE-ONLY] Merging existing batch outputs...")
        all_rows = merge_batches(tmp_dir, 0, prefix)
        _write_final(cleaned_data, all_rows, final_path)
        return

    # ----------------------------------------- Step 1: prepare prompt files
    gen = GeneratorAtomizeCopilot(
        temp_dir=tmp_dir,
        copilot_cmd="copilot.cmd",
        project_root=project_root,
    )

    pending = []
    for batch_idx, case_ids in enumerate(batches, start=1):
        label = f"Batch {batch_idx} ({case_ids[0]}..{case_ids[-1]})"
        output_path = os.path.join(tmp_dir, f"{prefix}{batch_idx}_output.json")

        if os.path.exists(output_path):
            print(f"[BATCH {batch_idx}] output already exists — will reuse in merge")
            continue

        prompt_path = gen.write_prompt_file(
            cleaned_data=cleaned_data,
            case_ids=case_ids,
            output_path=output_path,
            batch_label=f"batch{batch_idx}",
        )
        kb = os.path.getsize(prompt_path) // 1024
        print(f"[BATCH {batch_idx}] prompt ready: {os.path.basename(prompt_path)}  ({kb} KB)")
        pending.append((prompt_path, output_path, label))

    if not pending:
        print("\n[INFO] All batch outputs already exist — skipping to merge.")
    elif args.prepare_only:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        ps1_path = os.path.join(tmp_dir, f"run_atomize_batches_{ts}.ps1")
        build_ps1_runner(pending, ps1_path)
        print(f"\n[PREPARE-ONLY] PS1 runner written to:\n  {ps1_path}")
        print("\nRun it in PowerShell:")
        print(f'  & "{ps1_path}"')
        print("\nThen re-run with --merge-only to merge outputs.")
        return
    else:
        # --------------------------------------- Step 2: run PS1
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        ps1_path = os.path.join(tmp_dir, f"run_atomize_batches_{ts}.ps1")
        build_ps1_runner(pending, ps1_path)
        print(f"\n[COPILOT] Running {len(pending)} batch(es) via PowerShell console...")
        print(f"  PS1: {ps1_path}")
        rc = run_ps1(ps1_path, project_root)
        if rc != 0:
            print(f"[ERROR] PS1 runner exited with code {rc}.")
            sys.exit(rc)
        print("[COPILOT] All batches done.")

    # ------------------------------------------------------------------ Step 3: merge
    print(f"\n{'='*60}")
    print("[MERGE] Building final output...")
    all_rows = merge_batches(tmp_dir, len(batches), prefix)
    _write_final(cleaned_data, all_rows, final_path)


def _write_final(cleaned_data: dict, all_rows: list, final_path: str) -> None:
    meta = dict(cleaned_data.get("meta", {}))
    meta["source"] = meta.get("source", final_path)
    meta["mode"] = "copilot_batched"
    meta["rows"] = len(all_rows)
    final_data = {"status": "ok", "meta": meta, "rows": all_rows}
    save_json(final_path, final_data)
    print(f"  total rows   : {len(all_rows)}")
    print(f"\n[ALL DONE] Final output: {final_path}")


if __name__ == "__main__":
    main()
